export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const SET_ALL_CLASSES = 'SET_ALL_CLASSES';
export const SET_STUDENTS_OF_CLASS = 'SET_STUDENTS_OF_CLASS';
export const SET_FILTER_OPTIONS = 'SET_FILTER_OPTIONS';
export const RESET_FILTER_OPTIONS = 'RESET_FILTER_OPTIONS'
